//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 09:04:23 p. m. ECT 
//


package com.aplicaciones13.documentos.estructuras.autorizacioncomprobanteresponse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aplicaciones13.documentos.estructuras.autorizacioncomprobanteresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aplicaciones13.documentos.estructuras.autorizacioncomprobanteresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes.Mensaje }
     * 
     */
    public RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes.Mensaje createRespuestaAutorizacionComprobanteAutorizacionesAutorizacionMensajesMensaje() {
        return new RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes.Mensaje();
    }

    /**
     * Create an instance of {@link RespuestaAutorizacionComprobante }
     * 
     */
    public RespuestaAutorizacionComprobante createRespuestaAutorizacionComprobante() {
        return new RespuestaAutorizacionComprobante();
    }

    /**
     * Create an instance of {@link RespuestaAutorizacionComprobante.Autorizaciones }
     * 
     */
    public RespuestaAutorizacionComprobante.Autorizaciones createRespuestaAutorizacionComprobanteAutorizaciones() {
        return new RespuestaAutorizacionComprobante.Autorizaciones();
    }

    /**
     * Create an instance of {@link RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes }
     * 
     */
    public RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes createRespuestaAutorizacionComprobanteAutorizacionesAutorizacionMensajes() {
        return new RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion.Mensajes();
    }

    /**
     * Create an instance of {@link RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion }
     * 
     */
    public RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion createRespuestaAutorizacionComprobanteAutorizacionesAutorizacion() {
        return new RespuestaAutorizacionComprobante.Autorizaciones.Autorizacion();
    }

}
