//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.28 at 10:44:45 a. m. ECT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ec.gob.sri.ws.autorizacion")
package com.aplicaciones13.documentos.estructuras.autorizacioncomprobanteresponse;
