//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.28 at 10:44:46 a. m. ECT 
//


package com.aplicaciones13.documentos.estructuras.guiaremision.v1_1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aplicaciones13.documentos.estructuras.guiaremision.v1_1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aplicaciones13.documentos.estructuras.guiaremision.v1_1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Detalle }
     * 
     */
    public Detalle createDetalle() {
        return new Detalle();
    }

    /**
     * Create an instance of {@link GuiaRemision.InfoAdicional }
     * 
     */
    public GuiaRemision.InfoAdicional createGuiaRemisionInfoAdicional() {
        return new GuiaRemision.InfoAdicional();
    }

    /**
     * Create an instance of {@link InfoTributaria }
     * 
     */
    public InfoTributaria createInfoTributaria() {
        return new InfoTributaria();
    }

    /**
     * Create an instance of {@link Destinatario.Detalles }
     * 
     */
    public Destinatario.Detalles createDestinatarioDetalles() {
        return new Destinatario.Detalles();
    }

    /**
     * Create an instance of {@link Detalle.DetallesAdicionales.DetAdicional }
     * 
     */
    public Detalle.DetallesAdicionales.DetAdicional createDetalleDetallesAdicionalesDetAdicional() {
        return new Detalle.DetallesAdicionales.DetAdicional();
    }

    /**
     * Create an instance of {@link MaquinaFiscal }
     * 
     */
    public MaquinaFiscal createMaquinaFiscal() {
        return new MaquinaFiscal();
    }

    /**
     * Create an instance of {@link Destinatario }
     * 
     */
    public Destinatario createDestinatario() {
        return new Destinatario();
    }

    /**
     * Create an instance of {@link GuiaRemision }
     * 
     */
    public GuiaRemision createGuiaRemision() {
        return new GuiaRemision();
    }

    /**
     * Create an instance of {@link Detalle.DetallesAdicionales }
     * 
     */
    public Detalle.DetallesAdicionales createDetalleDetallesAdicionales() {
        return new Detalle.DetallesAdicionales();
    }

    /**
     * Create an instance of {@link GuiaRemision.InfoGuiaRemision }
     * 
     */
    public GuiaRemision.InfoGuiaRemision createGuiaRemisionInfoGuiaRemision() {
        return new GuiaRemision.InfoGuiaRemision();
    }

    /**
     * Create an instance of {@link GuiaRemision.Destinatarios }
     * 
     */
    public GuiaRemision.Destinatarios createGuiaRemisionDestinatarios() {
        return new GuiaRemision.Destinatarios();
    }

    /**
     * Create an instance of {@link GuiaRemision.InfoAdicional.CampoAdicional }
     * 
     */
    public GuiaRemision.InfoAdicional.CampoAdicional createGuiaRemisionInfoAdicionalCampoAdicional() {
        return new GuiaRemision.InfoAdicional.CampoAdicional();
    }

}
