//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.22 at 03:08:21 PM ECT 
//


package com.aplicaciones13.documentos.estructuras.comprobanteretencion.v2_0_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for compraCajBanano complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="compraCajBanano">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numCajBan" type="{}numCajBan"/>
 *         &lt;element name="precCajBan" type="{}precCajBan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compraCajBanano", propOrder = {
    "numCajBan",
    "precCajBan"
})
public class CompraCajBanano {

    @XmlElement(required = true)
    protected String numCajBan;
    @XmlElement(required = true)
    protected BigDecimal precCajBan;

    /**
     * Gets the value of the numCajBan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCajBan() {
        return numCajBan;
    }

    /**
     * Sets the value of the numCajBan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCajBan(String value) {
        this.numCajBan = value;
    }

    /**
     * Gets the value of the precCajBan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrecCajBan() {
        return precCajBan;
    }

    /**
     * Sets the value of the precCajBan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecCajBan(BigDecimal value) {
        this.precCajBan = value;
    }

}
